name: rhosts_env
channels:
  - conda-forge
  - defaults
  - anaconda
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - appnope=0.1.2
  - asttokens=2.0.5
  - backcall=0.2.0
  - brotli=1.0.9
  - brotli-python=1.0.9
  - ca-certificates=2025.2.25
  - comm=0.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=0.8.3
  - freetype=2.13.3
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.10
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.4.5
  - ipykernel=6.29.5
  - ipython=8.12.2
  - jedi=0.19.1
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=14.0.6
  - libdeflate=1.22
  - libffi=3.4.4
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libiconv=1.18
  - liblapack=3.9.0
  - libopenblas=0.3.25
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libxml2=2.13.7
  - libxslt=1.1.39
  - llvm-openmp=20.1.2
  - lxml=4.9.1
  - lz4-c=1.9.4
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.1
  - nibabel=5.2.1
  - nilearn=0.10.4
  - openjpeg=2.5.2
  - openssl=3.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=3.10.0
  - pooch=1.8.2
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.22
  - pygments=2.15.1
  - pysocks=1.7.1
  - python=3.8.20
  - python-dateutil=2.9.0post0
  - python-tzdata=2024.2
  - python_abi=3.8
  - pyzmq=25.1.2
  - readline=8.2
  - requests=2.32.3
  - scipy=1.10.1
  - seaborn=0.13.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - wcwidth=0.2.5
  - wheel=0.44.0
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - anyio==4.5.2
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.3
      - bleach==6.1.0
      - cechmate==0.1.0
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - dir-tree==0.0.2
      - exceptiongroup==1.2.2
      - fastjsonschema==2.21.1
      - fonttools==4.56.0
      - fqdn==1.5.1
      - h11==0.14.0
      - h5py==3.11.0
      - hopcroftkarp==1.2.5
      - httpcore==1.0.7
      - httpx==0.28.1
      - isoduration==20.11.0
      - jinja2==3.1.6
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kiwisolver==1.4.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - mistune==3.1.3
      - nbclient==0.10.1
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - notebook==7.3.3
      - notebook-shim==0.2.4
      - numpy==1.24.4
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.0.3
      - pandocfilters==1.5.1
      - persim==0.3.8
      - phat==1.5.0
      - pkgutil-resolve-name==1.3.10
      - prometheus-client==0.21.1
      - pybind11==2.13.6
      - pyparsing==3.1.4
      - python-json-logger==3.3.0
      - pytz==2025.1
      - pyyaml==6.0.2
      - referencing==0.35.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.0.0
      - rpds-py==0.20.1
      - scikit-learn==1.3.2
      - send2trash==1.8.3
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - terminado==0.18.1
      - tinycss2==1.2.1
      - tomli==2.2.1
      - types-python-dateutil==2.9.0.20241206
      - tzdata==2025.1
      - uri-template==1.3.0
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - wrapt==1.17.2
