name: rhosts
channels:
  - conda-forge
channel_priority: strict
dependencies:
  - python=3.8.20
  - pip=24.2
  - ipykernel=6.29.5
  - ipython=8.12.2
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - matplotlib-base=3.7.*
  - matplotlib-inline=0.1.6
  - networkx=3.1
  - numpy=1.24.*
  - pandas=2.0.*
  - pillow  # senza versione: lascia scegliere a conda
  - psutil
  - scipy=1.10.*
  - scikit-learn=1.3.*
  - seaborn=0.13.*
  - traitlets=5.14.3
  - tornado=6.4.*
  - typing_extensions=4.11.*
  - pyzmq
  - requests=2.32.*
  - urllib3=2.2.*
  - nibabel=5.2.*
  - nilearn=0.10.*
  # niente pin su icu/libpng/libtiff/libxml2/libdeflate/zlib/openssl/tk ecc.
  - pip:
      - anyio==4.5.2
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.3
      - bleach==6.1.0
      - cechmate==0.1.0
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - dir-tree==0.0.2
      - exceptiongroup==1.2.2
      - fastjsonschema==2.21.1
      - fonttools==4.56.0
      - fqdn==1.5.1
      - h11==0.14.0
      - h5py==3.11.0
      - hopcroftkarp==1.2.5
      - httpcore==1.0.7
      - httpx==0.28.1
      - isoduration==20.11.0
      - jinja2==3.1.6
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kiwisolver==1.4.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - mistune==3.1.3
      - nbclient==0.10.1
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - notebook==7.3.3
      - notebook-shim==0.2.4
      - overrides==7.7.0
      - packaging==24.2
      - pandocfilters==1.5.1
      - persim==0.3.8
      - pkgutil-resolve-name==1.3.10
      - prometheus-client==0.21.1
      - pybind11==2.13.6
      - pyparsing==3.1.4
      - python-json-logger==3.3.0
      - referencing==0.35.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.0.0
      - rpds-py==0.20.1
      - send2trash==1.8.3
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - terminado==0.18.1
      - tinycss2==1.2.1
      - tomli==2.2.1
      - types-python-dateutil==2.9.0.20241206
      - tzdata==2025.1
      - uri-template==1.3.0
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - wrapt==1.17.2
